services:
  postgres:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: admin
      POSTGRES_USER: admin
      POSTGRES_DB: users
    ports:
      - 5432:5432
    volumes:
      - ~./postgres-data:/var/lib/postgresql/data
