# execute build and run the application
start:
	./scripts/start.sh start

# start application with native image
native-start:
	./scripts/start.sh native-start

# stop the application
stop:
	./scripts/stop.sh
