server.port: 8080

spring:
  security:
    ignore: /actuator/health
    oauth2:
      authorizationserver:
        client:
          client-1:
            registration:
              client-id: client
              client-secret: "{bcrypt}$2a$10$DnsXtxr4rGdN1nerVO4f1OcIGry5ZIO5fmBzDpIgVBjrnh8mQhDHS" # example
              client-authentication-methods:
                - client_secret_basic
              authorization-grant-types:
                - client_credentials
                - authorization_code
                - refresh_token
              redirect-uris:
                # It uses 127.0.0.1 because cookies are not unique by port. Only by hosts
                - http://127.0.0.1:8082/login/oauth2/code/spring
              scopes:
                - user.read
                - user.write
                - openid
            require-authorization-consent: true
  threads:
    virtual:
      enabled: true
