server.port: 8888

spring:
  application:
    name: config-server
  cloud:
    refresh:
      enabled: false # This configuration is necessary to generate native images as described here https://github.com/spring-cloud/spring-cloud-config/issues/2365#issuecomment-1849992111
    config:
      server:
        git:
          uri: https://github.com/valdemarjuniorr/general-configuration-server
  threads:
    virtual:
      enabled: true

management:
  endpoints:
    web:
      exposure:
        include: "*"
