version: "3.8"
services:
  rabbitmq:
    image: rabbitmq:3.11.9-alpine
    environment:
      - RABBIT_USERNAME=guest
      - RABBIT_PASSWORD=guest
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - ~/.docker-conf/rabbitmq/data/:/var/lib/rabbitmq/
      - ~/.docker-conf/rabbitmq/log/:/var/log/rabbitmq
    networks:
      - rabbitmq_go_net
networks:
  rabbitmq_go_net:
    driver: bridge