services:
  rabbitmq:
    image: rabbitmq:3.13.1-alpine
    environment:
      - RABBIT_USERNAME=guest
      - RABBIT_PASSWORD=guest
    ports:
      - "5672:5672"
    volumes:
      - rabbitmq-data:/var/lib/rabbitmq/
      - rabbitmq-log:/var/log/rabbitmq
    networks:
      - rabbitmq_go_net
networks:
  rabbitmq_go_net:
    driver: bridge
# To make it work using rancher desktop https://stackoverflow.com/a/76292802/6230377
volumes:
  rabbitmq-data:
  rabbitmq-log: