spring:
  application.name: localstack-example
  cloud:
    config.enabled: false
    aws:
      credentials:
        access-key: ANUJDEKAVADIYAEXAMPLE
        secret-key: 2QvM4/Tdmf38SkcD/qalvXO4EXAMPLEKEY
      region:
        static: us-east-1
      endpoint: http://localhost:4566
      sns:
        enabled: true # default value, it can be omitted
#        endpoint: http://localhost:4566
        region: us-east-1 # default value us-east-1
      sqs:
        enabled: true # default value, it can be omitted
#        endpoint: http://localhost:4566
        region: us-east-1 # default value us-east-1
        listener:
          max-inflight-messages-per-queue: 10 # default value
          max-messages-per-poll: 10 # default value
          poll-timeout: 10 # default value in seconds
  config:
    import:

# Qeues names
events:
  topic: notification-topic
  queue: notification-queue