spring:
  application.name: localstack-example
  cloud:
    config:
      enabled: false

cloud:
  aws:
    region:
      static: us-east-1
    credentials:
      access-key: ANUJDEKAVADIYAEXAMPLE
      secret-key: 2QvM4/Tdmf38SkcD/qalvXO4EXAMPLEKEY
    endpoint:
      uri: http://localhost:4566

events:
  topic: notification-topic
  queue: notification-queue
