spring:
  application.name: localstack-example
  cloud:
    config:
      enabled: false
  threads:
    virtual:
      enabled: true
cloud:
  aws:
    region:
      static: us-east-1

events:
  topic: notification-topic
  queue: notification-queue
