spring:
  application:
    name: modulith-example
  datasource:
    url: jdbc:postgresql://localhost:5432/mydatabase
    username: myuser
    password: secret
  docker:
    compose:
      lifecycle-management: start_only # Start the container once
  modulith:
    events:
      jdbc:
        schema-initialization:
          enabled: true
      republish-outstanding-events-on-restart: true
  sql:
    init:
      mode: always
  threads:
    virtual:
      enabled: true
